import type { ReactNode } from "react";
import { Activity, BarChart3, ShieldAlert, Target } from "lucide-react";

type IntelligencePanelProps = { summary: any; equity: any };

const display = (value: unknown, suffix = "") => value == null ? "NO SAMPLE" : `${typeof value === "number" ? value.toFixed(2) : value}${suffix}`;
const pct = (value: unknown) => value == null ? "NO SAMPLE" : `${Number(value).toFixed(1)}%`;
const label = (value: string) => value.replaceAll("_", " ");

function Metric({ title, value, note }: { title: string; value: ReactNode; note?: string }) {
  return <div className="rounded-lg border border-white/[.07] bg-white/[.02] p-3"><p className="text-[9px] font-semibold uppercase tracking-[.13em] text-slate-500">{title}</p><p className="mt-1 text-base font-semibold text-slate-100">{value}</p>{note ? <p className="mt-1 text-[10px] leading-4 text-slate-500">{note}</p> : null}</div>;
}

function GroupTable({ title, rows, columns = ["trials", "completed", "wins", "winRate", "averageR", "sampleQuality"] }: { title: string; rows?: any[]; columns?: string[] }) {
  const data = rows ?? [];
  return <section className="rounded-xl border border-white/[.07] bg-white/[.018] p-4"><div className="flex items-center gap-2"><BarChart3 className="h-4 w-4 text-cyan-300" /><h3 className="text-sm font-semibold text-slate-100">{title}</h3></div>{data.length ? <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-[10px]"><thead className="text-[9px] uppercase tracking-[.12em] text-slate-500"><tr><th className="pb-2 pr-3">Group</th>{columns.map(column => <th key={column} className="pb-2 pr-3">{label(column)}</th>)}</tr></thead><tbody>{data.map((row, index) => <tr key={`${row.strategy ?? row.timeframe ?? row.direction ?? row.regime ?? row.qualification ?? row.setupQuality ?? row.dataQuality ?? row.provider ?? index}`} className="border-t border-white/[.05] text-slate-300"><td className="py-2 pr-3 font-semibold text-slate-100">{label(String(row.strategy ?? row.timeframe ?? row.direction ?? row.regime ?? row.qualification ?? row.setupQuality ?? row.dataQuality ?? row.provider ?? "UNAVAILABLE"))}</td>{columns.map(column => <td key={column} className="py-2 pr-3">{column === "winRate" ? pct(row[column]) : column === "averageR" ? display(row[column], "R") : row[column] === "sampleQuality" ? label(String(row[column])) : display(row[column])}</td>)}</tr>)}</tbody></table></div> : <p className="mt-3 rounded-lg border border-dashed border-white/[.08] p-4 text-center text-xs text-slate-500">NO SAMPLE · This comparison requires persisted Auto Paper evidence.</p>}</section>;
}

function OutcomeList({ title, rows }: { title: string; rows?: any[] }) {
  const data = rows ?? [];
  return <section className="rounded-xl border border-white/[.07] bg-white/[.018] p-4"><div className="flex items-center gap-2"><Target className="h-4 w-4 text-amber-300" /><h3 className="text-sm font-semibold text-slate-100">{title}</h3></div>{data.length ? <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.map(row => <div key={row.label} className="rounded-lg border border-white/[.06] bg-white/[.02] p-3"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">{row.label}</p><p className="mt-1 text-lg font-semibold text-slate-100">{row.count}</p><p className="text-[10px] text-slate-500">{pct(row.percentage)}</p></div>)}</div> : <p className="mt-3 text-xs text-slate-500">NO SAMPLE · No persisted lifecycle outcomes are available.</p>}</section>;
}

export function AutoPaperIntelligencePanel({ summary, equity }: IntelligencePanelProps) {
  const intelligence = summary?.intelligence;
  const completed = summary?.completed ?? 0;
  const sample = intelligence?.sampleQuality ?? "VERY SMALL SAMPLE";
  const noSample = !intelligence || !summary || completed === 0;
  const strategyRows = intelligence?.strategy ?? summary?.byStrategy;
  const timeframeRows = intelligence?.timeframe ?? summary?.byTimeframe;
  const directionRows = intelligence?.direction ?? summary?.byDirection;
  const regimeRows = intelligence?.regime;
  const qualificationRows = intelligence?.qualification;
  const setupQualityRows = intelligence?.setupQuality;
  const dataQualityRows = intelligence?.dataQuality;
  const providerRows = intelligence?.provider;
  const dataUnavailableCount = intelligence?.dataUnavailableCount ?? "—";
  const topStrategy = (strategyRows ?? []).filter((row: any) => row.averageR != null && row.completed >= 5).sort((a: any, b: any) => Number(b.averageR) - Number(a.averageR))[0];
  const topTimeframe = (timeframeRows ?? []).filter((row: any) => row.averageR != null && row.completed >= 5).sort((a: any, b: any) => Number(b.averageR) - Number(a.averageR))[0];
  return <section className="mt-5 space-y-4" aria-labelledby="performance-intelligence-title">
    <div className="rounded-xl border border-cyan-300/20 bg-cyan-300/[.035] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-cyan-300">PERFORMANCE INTELLIGENCE</p><h2 id="performance-intelligence-title" className="mt-1 text-lg font-semibold text-slate-100">Learning from simulation, not changing the strategy</h2><p className="mt-1 max-w-3xl text-[11px] leading-5 text-slate-400">All values are returned by the owner-scoped Auto Paper performance contract. Current rules, scores, thresholds, providers, and lifecycle behavior remain unchanged.</p></div><span className="rounded-full border border-amber-300/20 bg-amber-300/[.06] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.1em] text-amber-100">{label(sample)}</span></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7"><Metric title="Total Trials" value={summary?.totalTrials ?? "—"} /><Metric title="Completed" value={completed} /><Metric title="Wins" value={summary?.wins ?? "—"} /><Metric title="Losses" value={summary?.losses ?? "—"} /><Metric title="Open" value={summary?.open ?? "—"} /><Metric title="Data Unavailable" value={dataUnavailableCount} /><Metric title="Win Rate" value={summary?.winRate == null ? "NO SAMPLE" : pct(summary.winRate)} /></div><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6"><Metric title="Average R" value={display(summary?.averageR, "R")} /><Metric title="Total R" value={display(summary?.totalR, "R")} /><Metric title="Average P&L" value={display(intelligence?.averagePnl)} /><Metric title="Total P&L" value={display(intelligence?.totalPnl)} /><Metric title="Maximum Drawdown" value={display(summary?.maximumDrawdown)} /><Metric title="Profit Factor" value={display(summary?.profitFactor)} /></div><p className="mt-3 text-[11px] text-slate-500">{noSample ? "VERY SMALL SAMPLE · Results are exploratory." : `${label(sample)} · Results are observational and not statistical significance.`}</p></div>
    <div className="grid gap-4 xl:grid-cols-2"><GroupTable title="STRATEGY PERFORMANCE" rows={strategyRows} /><GroupTable title="SCALP vs SWING" rows={strategyRows?.filter((row: any) => ["SCALP", "SWING", "15M FAST SCALP"].includes(String(row.strategy)))} columns={["trials", "completed", "winRate", "averageR", "totalR", "sampleQuality"]} /></div>
    <div className="grid gap-4 xl:grid-cols-2"><GroupTable title="TIMEFRAME INTELLIGENCE" rows={timeframeRows} columns={["trials", "completed", "winRate", "averageR", "pnl", "sampleQuality"]} /><GroupTable title="DIRECTION INTELLIGENCE" rows={directionRows} columns={["trials", "completed", "winRate", "averageR", "totalR", "sampleQuality"]} /></div>
    <div className="grid gap-4 xl:grid-cols-2"><GroupTable title="MARKET REGIME INTELLIGENCE" rows={regimeRows} columns={["trials", "completed", "winRate", "averageR", "pnl", "sampleQuality"]} /><GroupTable title="QUALIFICATION INTELLIGENCE" rows={qualificationRows} columns={["trials", "completed", "winRate", "averageR", "sampleQuality"]} /></div>
    <div className="grid gap-4 xl:grid-cols-2"><GroupTable title="SETUP QUALITY INTELLIGENCE" rows={setupQualityRows} columns={["trials", "completed", "winRate", "averageR", "sampleQuality"]} /><GroupTable title="DATA QUALITY" rows={dataQualityRows} columns={["trials", "completed", "winRate", "averageR", "sampleQuality"]} /></div>
    <GroupTable title="PROVIDER INTELLIGENCE · ANALYTICS ONLY" rows={providerRows} columns={["trials", "completed", "winRate", "averageR", "dataQuality", "sampleQuality"]} />
    <div className="grid gap-4 xl:grid-cols-3"><OutcomeList title="TARGET LADDER ANALYSIS" rows={intelligence?.targetLadder} /><OutcomeList title="HOW TRADES END" rows={intelligence?.exits} /><OutcomeList title="WHY TRADES FAIL" rows={intelligence?.failures} /></div>
    <div className="grid gap-4 xl:grid-cols-2"><OutcomeList title="R DISTRIBUTION" rows={intelligence?.rDistribution} /><section className="rounded-xl border border-white/[.07] bg-white/[.018] p-4"><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-cyan-300" /><h3 className="text-sm font-semibold text-slate-100">EQUITY & DRAWDOWN INTELLIGENCE</h3></div>{equity?.state === "READY" ? <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3"><Metric title="Starting Capital" value={display(equity.startingCapital)} /><Metric title="Current Equity" value={display(equity.currentEquity)} /><Metric title="Realized P&L" value={display(equity.realizedPnl)} /><Metric title="Unrealized P&L" value={display(equity.unrealizedPnl)} /><Metric title="Peak Equity" value={display(equity.peakEquity)} /><Metric title="Maximum Drawdown" value={display(equity.maximumDrawdown)} /></div> : <p className="mt-3 rounded-lg border border-dashed border-white/[.08] p-5 text-center text-xs text-slate-500">NO EQUITY HISTORY · Existing snapshots do not yet provide a curve.</p>}</section></div>
    <section className="rounded-xl border border-emerald-300/15 bg-emerald-300/[.025] p-4"><div className="flex items-center gap-2"><ShieldAlert className="h-4 w-4 text-emerald-300" /><h3 className="text-sm font-semibold text-emerald-100">WHAT ARE WE LEARNING?</h3></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{topStrategy ? <p className="rounded-lg border border-white/[.06] bg-white/[.02] p-3 text-xs text-slate-300">{label(String(topStrategy.strategy))} currently has the strongest observed Average R among groups with at least five completed trials; {label(String(topStrategy.sampleQuality))} applies.</p> : <p className="rounded-lg border border-white/[.06] bg-white/[.02] p-3 text-xs text-slate-500">INSUFFICIENT SAMPLE · No strategy comparison is reliable yet.</p>}{topTimeframe ? <p className="rounded-lg border border-white/[.06] bg-white/[.02] p-3 text-xs text-slate-300">{label(String(topTimeframe.timeframe))} currently leads the observed timeframe comparison; this is exploratory evidence, not a trading recommendation.</p> : <p className="rounded-lg border border-white/[.06] bg-white/[.02] p-3 text-xs text-slate-500">INSUFFICIENT SAMPLE · No timeframe comparison is reliable yet.</p>}</div></section>
    <p className="text-[10px] leading-4 text-slate-500">Read-only analytics. This view does not enable or disable Auto Paper, create trials/accounts/snapshots, modify presets, change scoring, or route providers. It never generates BUY, SELL, guaranteed, or profitable claims.</p>
  </section>;
}
