import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { usePwaStatus } from "@/pwa/PwaStatus";
import { ArrowLeft, ArrowUpRight, CircleAlert, CircleCheck, Clock3, Eye, Layers3, Loader2, ShieldCheck, Target } from "lucide-react";

type LowPlan = {
  assetId: string; symbol: string; displaySymbol: string; actionable: boolean; presentationStatus: "QUALIFIED" | "WATCH" | "NO TRADE"; rank: number | null; direction: "LONG" | "SHORT" | "NO TRADE"; expectedDuration: string | null; provider: string | null; providerSymbol: string | null; dataTimestamp: number | null;
  dataBundle: { state: "VALID" | "PARTIAL" | "STALE" | "MISSING" | "INCOHERENT"; coherent: boolean; eligibleForScalping: boolean; capturedAt: number; statusMessage: string; timeframes: Array<{ timeframe: "1m" | "3m" | "5m"; provider: string | null; symbol: string | null; state: "VALID" | "STALE" | "MISSING" | "INVALID"; status: "live" | "stale" | "unavailable"; fetchedAt: number | null; candleCount: number; oldestCandleAt: number | null; newestCandleAt: number | null; freshnessMs: number | null; eligibleForScalping: boolean; message: string | null; errorClass: string | null }> };
  currentPrice: number | null; alignment: "STRONG" | "PARTIAL" | "CONFLICTED" | "NEUTRAL" | "UNAVAILABLE";
  timeframeStates: Array<{ timeframe: "1m" | "3m" | "5m"; bias: "bullish" | "neutral" | "bearish"; price: number; rsi: number | null; atrPercent: number | null; volumeExpansion: number | null; momentum: string; structure: string; evidence: string[]; risks: string[] }>;
  setupQuality: { value: number | null; label: "Scalping Setup Quality"; detail: string };
  entryZone: { low: number; high: number; preferred: number; reason: string; state: "READY" | "ENTRY MISSED" } | null;
  stop: { price: number; reason: string; distancePercent: number | null } | null; invalidation: { price: number; reason: string } | null;
  targets: Array<{ label: "TP1" | "TP2" | "TP3"; price: number; distancePercent: number | null; rewardRisk: number | null; reason: string; priority: string }>;
  rewardRisk: number | null; targetPath: Array<{ label: "ENTRY" | "TP1" | "TP2" | "TP3"; price: number; status: "CURRENT" | "REACHED" | "PENDING" }>; evidence: string[]; risks: string[]; noTradeReasons: string[];
};
type LowResponse = { generatedAt: number; provider: string; requiredTimeframes: string[]; minimumCandles: number; providerDocumentation: { kline: string; instruments: string; rateLimits: string; terms: string }; summary: { evaluatedAssets: number; qualified: number; watch: number; noTrade: number; dataUnavailable: number; byBundleState: Array<{ state: string; count: number }> }; note: string; setups: LowPlan[] };

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 6 });
const asTime = (value: number | null) => value ? new Date(value).toLocaleString() : "UNAVAILABLE";
const ago = (value: number | null) => value === null ? "UNAVAILABLE" : `${Math.max(0, Math.round((Date.now() - value) / 1_000))}s ago`;

export function LowTimeframeScalpingWorkspace({ onBack, onInspectAsset, onPaperTrade, onShowEstablished }: { onBack: () => void; onInspectAsset: (assetId: string) => void; onPaperTrade: (assetId: string) => void; onShowEstablished: () => void }) {
  const { online } = usePwaStatus();
  const query = trpc.crypto.lowTimeframeScalping.useQuery(undefined, { enabled: online, staleTime: 20_000, refetchOnWindowFocus: false, retry: 1 });
  const data = query.data as LowResponse | undefined;
  return <div className="space-y-6 pb-20">
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-white/[.07] pb-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300/[.12] text-cyan-200"><Target className="h-5 w-5" /></span><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-cyan-200">Verified low-timeframe layer</p><h2 className="mt-1 text-xl font-semibold tracking-tight">Scalping Intelligence</h2><p className="mt-2 max-w-3xl text-xs leading-5 text-slate-400">An isolated 1m / 3m / 5m analysis path. It uses only complete coherent Bybit Spot candles and does not modify Opportunity Score, Regime Score, Swing, alerts, or Paper Trading economics.</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={onShowEstablished} className="border-white/[.1] text-slate-300"><Layers3 className="mr-1.5 h-3.5 w-3.5" />View established 15M Scalping</Button><a href={data?.providerDocumentation.kline ?? "https://bybit-exchange.github.io/docs/v5/market/kline"} target="_blank" rel="noreferrer" className="inline-flex items-center rounded-md border border-white/[.1] px-3 py-1.5 text-[11px] text-slate-400 hover:text-slate-100">Provider documentation</a><a href={data?.providerDocumentation.terms ?? "https://www.bybit.com/en/help-center/article/Terms-of-Service"} target="_blank" rel="noreferrer" className="inline-flex items-center rounded-md border border-white/[.1] px-3 py-1.5 text-[11px] text-slate-400 hover:text-slate-100">Provider terms</a></div></div></div><Button variant="outline" onClick={onBack} className="border-white/[.1] bg-white/[.025] text-slate-200"><ArrowLeft className="mr-2 h-4 w-4" />Back to Dashboard</Button></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Status label="Required evidence" value="1M · 3M · 5M" tone="cyan" /><Status label="Provider" value={data?.provider ?? "Bybit Spot"} tone="violet" /><Status label="Validated depth" value={data ? `${data.minimumCandles} closed / timeframe` : "Validating"} tone="cyan" /><Status label="Capture" value={data ? ago(data.generatedAt) : "UNAVAILABLE"} tone="amber" /></section>
    {!online ? <div role="status" className="rounded-xl border border-amber-300/25 bg-amber-300/[.06] p-4 text-xs text-amber-100"><strong>OFFLINE · READ ONLY.</strong> No low-timeframe setup or Paper Trading action is generated without a live validated provider response.</div> : null}
    {query.isLoading ? <Loading /> : query.error ? <ErrorPanel detail={query.error.message} /> : data ? <><Overview data={data} /><TimeframeAvailability data={data} onShowEstablished={onShowEstablished} />{data.setups.map((plan, index) => <LowSetupCard key={plan.assetId} plan={plan} ordinal={plan.rank ?? index + 1} online={online} onInspect={() => onInspectAsset(plan.assetId)} onPaperTrade={() => onPaperTrade(plan.assetId)} />)}</> : <Empty />}
  </div>;
}

function Overview({ data }: { data: LowResponse }) { return <section className="rounded-2xl border border-cyan-300/15 bg-cyan-300/[.025] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-cyan-200">Current low-timeframe overview</p><h3 className="mt-1 text-sm font-semibold text-slate-100">{data.summary.evaluatedAssets} assets evaluated · {data.summary.qualified} qualified · {data.summary.watch} watch · {data.summary.noTrade} no trade</h3></div><p className="max-w-xl text-xs leading-5 text-slate-400">{data.note}</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-5"><Mini label="Valid bundles" value={String(data.summary.byBundleState.find(item => item.state === "VALID")?.count ?? 0)} note="Only these may be analyzed" /><Mini label="Partial" value={String(data.summary.byBundleState.find(item => item.state === "PARTIAL")?.count ?? 0)} note="Not used" tone="risk" /><Mini label="Stale" value={String(data.summary.byBundleState.find(item => item.state === "STALE")?.count ?? 0)} note="No new entry" tone="amber" /><Mini label="Missing" value={String(data.summary.byBundleState.find(item => item.state === "MISSING")?.count ?? 0)} note="No provider fallback" tone="risk" /><Mini label="Incoherent" value={String(data.summary.byBundleState.find(item => item.state === "INCOHERENT")?.count ?? 0)} note="No mixing permitted" tone="risk" /></div></section>; }

function TimeframeAvailability({ data, onShowEstablished }: { data: LowResponse; onShowEstablished: () => void }) {
  const stateFor = (timeframe: "1m" | "3m" | "5m") => {
    const rows = data.setups.flatMap(plan => plan.dataBundle.timeframes).filter(item => item.timeframe === timeframe);
    if (!rows.length) return "UNAVAILABLE";
    return rows.some(item => item.status === "live" && item.eligibleForScalping) ? "AVAILABLE" : "UNAVAILABLE";
  };
  return <section className="rounded-2xl border border-white/[.08] bg-white/[.018] p-4" aria-label="Scalp timeframe availability"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-cyan-200">TIMEFRAME AVAILABILITY</p><p className="mt-1 text-xs text-slate-400">Display-only provider state for the isolated low-timeframe layer. No unsupported timeframe is substituted.</p></div><Button type="button" variant="outline" onClick={onShowEstablished} className="min-h-11 border-cyan-300/20 text-[10px] text-cyan-100">VIEW 15M FAST SCALP</Button></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><TimeframeBadge label="1M" value={stateFor("1m")} /><TimeframeBadge label="3M" value={stateFor("3m")} /><TimeframeBadge label="5M" value={stateFor("5m")} /><TimeframeBadge label="15M FAST SCALP" value="SEPARATE ESTABLISHED VIEW" /></div></section>;
}
function TimeframeBadge({ label, value }: { label: string; value: string }) { const available = value === "AVAILABLE"; return <div className="rounded-xl border border-white/[.08] bg-black/10 p-3"><p className="font-mono text-[10px] font-semibold text-slate-300">{label}</p><p className={`mt-2 text-xs font-semibold uppercase ${available ? "text-emerald-200" : value === "SEPARATE ESTABLISHED VIEW" ? "text-cyan-200" : "text-rose-200"}`}>{value}</p></div>; }

function LowSetupCard({ plan, ordinal, online, onInspect, onPaperTrade }: { plan: LowPlan; ordinal: number; online: boolean; onInspect: () => void; onPaperTrade: () => void }) {
  const qualified = plan.presentationStatus === "QUALIFIED" && plan.actionable && plan.entryZone && plan.stop;
  const tone = qualified ? "border-emerald-300/20 bg-[#09111f]" : plan.presentationStatus === "WATCH" ? "border-amber-300/20 bg-amber-300/[.025]" : "border-slate-500/20 bg-slate-950/55";
  const badge = qualified ? "border-emerald-300/25 bg-emerald-300/[.07] text-emerald-100" : plan.presentationStatus === "WATCH" ? "border-amber-300/25 bg-amber-300/[.07] text-amber-100" : "border-slate-500/25 bg-slate-500/[.07] text-slate-300";
  const direction = plan.direction === "LONG" ? "border-emerald-300/25 bg-emerald-300/[.07] text-emerald-100" : plan.direction === "SHORT" ? "border-rose-300/25 bg-rose-300/[.07] text-rose-100" : "border-slate-500/25 bg-slate-500/[.07] text-slate-300";
  return <article className={`overflow-hidden rounded-2xl border ${tone}`}><div className="flex flex-wrap items-start justify-between gap-3 border-b border-white/[.06] px-5 py-4"><div className="flex items-center gap-3"><span className="font-mono text-xs text-slate-500">{qualified ? String(ordinal).padStart(2, "0") : "—"}</span><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold">{plan.displaySymbol}</h3><span className={`rounded-full border px-2 py-1 text-[10px] font-semibold tracking-wide ${badge}`}>{plan.presentationStatus}</span><span className={`rounded-full border px-2 py-1 text-[10px] font-semibold tracking-wide ${direction}`}>{plan.direction}</span>{plan.setupQuality.value !== null ? <span className="rounded-full border border-cyan-300/20 bg-cyan-300/[.06] px-2 py-1 text-[10px] font-semibold text-cyan-100">QUALITY {plan.setupQuality.value}/100</span> : null}</div><p className="mt-1 text-[11px] text-slate-500">{plan.provider ?? "UNAVAILABLE"} · captured {asTime(plan.dataTimestamp)} · alignment {plan.alignment} · setup quality is separate from Opportunity Score</p></div></div><div className="flex flex-wrap items-center gap-2"><Button size="sm" variant="outline" onClick={onInspect} className="border-white/[.1] text-slate-300"><Eye className="mr-1.5 h-3.5 w-3.5" />Asset Intelligence</Button>{qualified ? <Button size="sm" onClick={onPaperTrade} disabled={!online} className="bg-emerald-300 text-slate-950 hover:bg-emerald-200 disabled:bg-slate-600"><ArrowUpRight className="mr-1.5 h-3.5 w-3.5" />Paper {plan.direction}</Button> : null}</div></div>
    <Provenance plan={plan} />
    {qualified ? <div className="space-y-4 p-5"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Mini label="Current price" value={plan.currentPrice === null ? "UNAVAILABLE" : money.format(plan.currentPrice)} note="Latest completed 1m close" /><Mini label="Preferred entry" value={money.format(plan.entryZone!.preferred)} note={plan.entryZone!.reason} tone={plan.entryZone!.state === "READY" ? "positive" : "risk"} /><Mini label="Stop / invalidation" value={money.format(plan.stop!.price)} note={plan.stop!.reason} tone="risk" /><Mini label="Expected duration" value={plan.expectedDuration ?? "UNAVAILABLE"} note={`First target R:R ${plan.rewardRisk ?? "UNAVAILABLE"}:1`} /></div><div className="grid gap-2 sm:grid-cols-3">{plan.targets.map(target => <Mini key={target.label} label={`${target.label} · R:R ${target.rewardRisk ?? "—"}`} value={money.format(target.price)} note={`${target.distancePercent ?? "—"}% · ${target.reason}`} tone="positive" />)}</div><TargetPath path={plan.targetPath} /><Evidence title="Why this setup" items={plan.evidence} tone="positive" /><div className="rounded-xl border border-amber-300/15 bg-amber-300/[.035] p-3 text-[11px] leading-5 text-amber-100"><strong>Paper Trading boundary.</strong> Opening a user-confirmed simulation retains this immutable low-timeframe snapshot as evidence. Existing server-authoritative 4h-ATR / 2R accounting, authorization, manual close, and no-real-trading rules remain unchanged.</div></div> : <NoTrade plan={plan} />}
  </article>;
}

function Provenance({ plan }: { plan: LowPlan }) { const valid = plan.dataBundle.state === "VALID" && plan.dataBundle.coherent; return <section className={`border-b border-white/[.06] px-5 py-3 ${valid ? "bg-emerald-300/[.025]" : plan.dataBundle.state === "STALE" ? "bg-amber-300/[.025]" : "bg-rose-300/[.025]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-slate-400">Provider provenance and data quality</p><p className="mt-1 text-xs font-semibold text-slate-100">{plan.dataBundle.state} · {plan.dataBundle.coherent ? "ONE PROVIDER / COHERENT" : "NO PLAN"} · {plan.provider ?? "UNAVAILABLE"}</p></div><p className="max-w-2xl text-[11px] leading-4 text-slate-400">{plan.dataBundle.statusMessage}</p></div><div className="mt-3 grid gap-2 sm:grid-cols-3">{plan.dataBundle.timeframes.map(item => <div key={item.timeframe} className="rounded-lg border border-white/[.08] bg-black/10 p-2"><div className="flex items-center justify-between gap-2"><strong className="font-mono text-[11px] text-slate-100">{item.timeframe.toUpperCase()}</strong><span className={`text-[9px] font-semibold ${item.eligibleForScalping ? "text-emerald-200" : item.status === "stale" ? "text-amber-200" : "text-rose-200"}`}>{item.state}</span></div><p className="mt-1 truncate text-[10px] text-slate-400">{item.provider ?? "UNAVAILABLE"} · {item.symbol ?? "NO SYMBOL"}</p><p className="mt-1 text-[10px] text-slate-500">{item.candleCount} completed · freshness {item.freshnessMs === null ? "UNAVAILABLE" : `${Math.round(item.freshnessMs / 1_000)}s`}</p><p className="mt-1 truncate text-[10px] text-slate-600">{item.fetchedAt ? asTime(item.fetchedAt) : item.errorClass ?? item.message ?? "NO RESPONSE"}</p></div>)}</div></section>; }

function NoTrade({ plan }: { plan: LowPlan }) { return <div className="space-y-4 p-5"><div className="flex gap-3"><CircleAlert className="mt-0.5 h-5 w-5 shrink-0 text-slate-400" /><div><p className="font-semibold text-slate-100">{plan.presentationStatus === "WATCH" ? "WATCH — NOT A TRADE" : "NO TRADE — WHY?"}</p><p className="mt-1 text-sm leading-6 text-slate-400">{plan.noTradeReasons.join(" ") || "Current low-timeframe evidence did not support a valid plan."}</p><p className="mt-2 text-xs text-slate-500">No 1m/3m/5m series was synthesized, resampled, mixed, or used after becoming stale.</p></div></div><TimeframeStates states={plan.timeframeStates} /><Evidence title="Observed evidence" items={plan.evidence} tone="neutral" /><Evidence title="Risk / missing confirmation" items={plan.risks.length ? plan.risks : [plan.setupQuality.detail]} tone="risk" /></div>; }
function TimeframeStates({ states }: { states: LowPlan["timeframeStates"] }) { return states.length ? <div className="grid gap-2 sm:grid-cols-3">{states.map(state => <div key={state.timeframe} className="rounded-xl border border-white/[.07] bg-white/[.02] p-3"><div className="flex items-center justify-between"><strong className="font-mono text-xs text-slate-100">{state.timeframe.toUpperCase()}</strong><span className={state.bias === "bullish" ? "text-emerald-200" : state.bias === "bearish" ? "text-rose-200" : "text-slate-400"}>{state.bias.toUpperCase()}</span></div><p className="mt-2 text-[10px] text-slate-400">RSI {state.rsi ?? "—"} · volume {state.volumeExpansion ?? "—"}×</p><p className="mt-1 text-[10px] text-slate-500">Momentum {state.momentum} · structure {state.structure}</p></div>)}</div> : null; }
function TargetPath({ path }: { path: LowPlan["targetPath"] }) { return path.length ? <section className="rounded-xl border border-cyan-300/15 bg-cyan-300/[.025] p-3"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-cyan-200">Target path · current price position</p><div className="mt-3 flex flex-wrap gap-2">{path.map((step, index) => <div key={step.label} className="flex items-center gap-2"><div className={`rounded-lg border px-3 py-2 text-[10px] ${step.status === "REACHED" ? "border-emerald-300/20 bg-emerald-300/[.08] text-emerald-100" : step.status === "CURRENT" ? "border-cyan-300/25 bg-cyan-300/[.08] text-cyan-100" : "border-white/[.08] bg-black/10 text-slate-300"}`}><strong>{step.label}</strong><span className="ml-2 font-mono">{money.format(step.price)}</span><span className="ml-2 text-[9px]">{step.status}</span></div>{index < path.length - 1 ? <span className="text-slate-600">→</span> : null}</div>)}</div></section> : null; }
function Evidence({ title, items, tone }: { title: string; items: string[]; tone: "positive" | "risk" | "neutral" }) { const colors = tone === "positive" ? "border-emerald-300/15 bg-emerald-300/[.035] text-emerald-100" : tone === "risk" ? "border-amber-300/15 bg-amber-300/[.035] text-amber-100" : "border-white/[.08] bg-white/[.02] text-slate-200"; return <section className={`rounded-xl border p-4 ${colors}`}><div className="flex items-center gap-2"><CircleCheck className="h-4 w-4" /><h4 className="text-[10px] font-semibold uppercase tracking-[.15em]">{title}</h4></div><ul className="mt-3 space-y-1.5 text-xs leading-5">{items.length ? items.slice(0, 8).map(item => <li key={item}>• {item}</li>) : <li>• UNAVAILABLE</li>}</ul></section>; }
function Status({ label, value, tone }: { label: string; value: string; tone: "cyan" | "amber" | "violet" }) { const colors = tone === "cyan" ? "border-cyan-300/15 bg-cyan-300/[.035] text-cyan-100" : tone === "amber" ? "border-amber-300/15 bg-amber-300/[.035] text-amber-100" : "border-violet-300/15 bg-violet-300/[.035] text-violet-100"; return <div className={`rounded-xl border p-4 ${colors}`}><span className="text-[9px] font-semibold uppercase tracking-[.14em] opacity-70">{label}</span><p className="mt-2 text-xs font-medium">{value}</p></div>; }
function Mini({ label, value, note, tone = "neutral" }: { label: string; value: string; note: string; tone?: "neutral" | "positive" | "risk" | "amber" }) { const color = tone === "positive" ? "text-emerald-200" : tone === "risk" ? "text-rose-200" : tone === "amber" ? "text-amber-200" : "text-cyan-100"; return <div className="rounded-xl border border-white/[.07] bg-white/[.02] p-3"><span className="block text-[9px] font-semibold uppercase tracking-[.13em] text-slate-500">{label}</span><strong className={`mt-1 block break-words font-mono text-sm ${color}`}>{value}</strong><p className="mt-2 text-[10px] leading-4 text-slate-500">{note}</p></div>; }
function Loading() { return <div className="grid min-h-[40vh] place-items-center"><div className="text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-cyan-200" /><p className="mt-3 text-sm text-slate-400">Validating complete 1m / 3m / 5m provider bundles…</p></div></div>; }
function ErrorPanel({ detail }: { detail: string }) { return <div className="rounded-xl border border-rose-300/25 bg-rose-300/[.06] p-4 text-sm text-rose-100"><strong>Scalping Intelligence data is unavailable.</strong><p className="mt-1 text-xs text-rose-100/75">{detail}</p><p className="mt-2 text-xs text-rose-100/75">No fallback, fabricated, resampled, stale, or mixed-provider setup is shown.</p></div>; }
function Empty() { return <div className="rounded-2xl border border-dashed border-white/[.12] p-8 text-center text-sm text-slate-400">No low-timeframe response is available. The workspace will not construct a fallback setup.</div>; }
