import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { usePwaStatus } from "@/pwa/PwaStatus";
import { ArrowLeft, ArrowUpRight, CircleAlert, CircleCheck, Clock3, Eye, Loader2, Radar, ShieldAlert, Target } from "lucide-react";
import { useMemo, useState } from "react";

type Status = "QUALIFIED" | "POTENTIAL" | "WATCH" | "NO TRADE" | "DATA UNAVAILABLE";
type Filter = "ALL" | Status;
type DiscoveryItem = {
  assetId: string; symbol: string; status: Status; maturity: "EARLY" | "DEVELOPING" | "CONFIRMING" | "QUALIFIED" | "INVALIDATED" | "UNAVAILABLE"; tradeReadiness: "READY" | "WAITING" | "RESTRICTED" | "NOT ELIGIBLE" | "UNAVAILABLE"; paperTradeEligible: boolean; rank: number | null; opportunityScore: number | null; direction: "LONG" | "SHORT" | "NO TRADE"; provider: string | null; dataTimestamp: number | null; regime: { classification: string | null; restricted: boolean }; timeframeAgreement: { aligned: number; required: number; direction: string; label: string }; whyInteresting: string[]; whatWouldChange: string[]; conditionalEntry: string | null; exactReason: string; dataReason: string | null; sourcePlan: { entryZone: { preferred: number; reason: string } | null; stop: { price: number; reason: string } | null; targets: Array<{ label: string; price: number; reason: string }>; rewardRisk: number | null };
};
type Response = { generatedAt: number; marketRegime: { classification: string; score: number } | null; discovery: { items: DiscoveryItem[]; summary: { evaluated: number; qualified: number; potential: number; watch: number; noTrade: number; dataUnavailable: number; restrictedByRiskOff: number } } };

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 5 });
const tone: Record<Status, string> = { QUALIFIED: "border-emerald-300/25 bg-emerald-300/[.08] text-emerald-100", POTENTIAL: "border-amber-300/25 bg-amber-300/[.08] text-amber-100", WATCH: "border-cyan-300/25 bg-cyan-300/[.08] text-cyan-100", "NO TRADE": "border-rose-300/25 bg-rose-300/[.07] text-rose-100", "DATA UNAVAILABLE": "border-slate-400/20 bg-slate-400/[.06] text-slate-200" };
const time = (value: number | null) => value ? new Date(value).toLocaleString() : "UNAVAILABLE";

export function OpportunityDiscoveryWorkspace({ onBack, onInspectAsset, onPaperTrade }: { onBack: () => void; onInspectAsset: (assetId: string) => void; onPaperTrade: (assetId: string) => void }) {
  const { online } = usePwaStatus();
  const [filter, setFilter] = useState<Filter>("ALL");
  const query = trpc.crypto.tradeSetups.useQuery({ mode: "SWING" }, { enabled: online, staleTime: 30_000, refetchOnWindowFocus: false });
  const data = query.data as Response | undefined;
  const items = useMemo(() => (data?.discovery.items ?? []).filter(item => filter === "ALL" || item.status === filter), [data?.discovery.items, filter]);
  const summary = data?.discovery.summary;
  return <div className="space-y-6 pb-20">
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-white/[.07] pb-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300/[.12] text-cyan-200"><Radar className="h-5 w-5" /></span><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-cyan-200">Read-only discovery layer</p><h2 className="mt-1 text-xl font-semibold tracking-tight">Opportunity Discovery</h2><p className="mt-2 max-w-3xl text-xs leading-5 text-slate-400">Swing discovery separates data availability, technical opportunity quality, and trade readiness. It reuses existing 1H / 4H / 1D evidence and Opportunity Score; it does not change either score, provider policy, or entry rule.</p></div></div><Button variant="outline" onClick={onBack} className="border-white/[.1] bg-white/[.025] text-slate-200"><ArrowLeft className="mr-2 h-4 w-4" />Back to Dashboard</Button></header>
    {!online ? <section role="status" className="rounded-xl border border-amber-300/25 bg-amber-300/[.06] p-4 text-xs text-amber-100"><strong>OFFLINE · READ ONLY.</strong> Discovery requires a current server-validated Swing response. No Paper Trading action is available offline.</section> : null}
    {data?.marketRegime?.classification === "RISK OFF" ? <section className="rounded-2xl border border-rose-300/25 bg-rose-300/[.06] p-5"><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-rose-200" /><div><p className="font-semibold text-rose-100">RISK OFF</p><p className="mt-1 text-sm leading-6 text-rose-100/80">Market conditions are defensive. Potential and Watch setups remain visible for monitoring only; existing qualification and Paper Trading protections remain restricted.</p></div></div></section> : null}
    {query.isLoading ? <Loading /> : query.error ? <ErrorPanel detail={query.error.message} /> : data && summary ? <><Summary summary={summary} /><section className="flex flex-wrap gap-2" aria-label="Opportunity status filters">{(["ALL", "QUALIFIED", "POTENTIAL", "WATCH", "NO TRADE", "DATA UNAVAILABLE"] as Filter[]).map(value => <Button key={value} size="sm" variant="outline" onClick={() => setFilter(value)} className={`border-white/[.1] text-[11px] ${filter === value ? "bg-cyan-300/[.12] text-cyan-100" : "bg-white/[.02] text-slate-400"}`}>{value === "ALL" ? "All" : value}</Button>)}</section><section className="space-y-4">{items.length ? items.map(item => <DiscoveryCard key={item.assetId} item={item} online={online} onInspect={() => onInspectAsset(item.assetId)} onPaper={() => onPaperTrade(item.assetId)} />) : <Empty />}</section></> : <Empty />}
  </div>;
}

function Summary({ summary }: { summary: Response["discovery"]["summary"] }) { return <section className="rounded-2xl border border-cyan-300/15 bg-cyan-300/[.025] p-5"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-cyan-200">Current Swing discovery</p><h3 className="mt-1 text-sm font-semibold text-slate-100">{summary.evaluated} assets evaluated from one validated 1H / 4H / 1D interpretation pass</h3><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Qualified" value={summary.qualified} tone="emerald" /><Metric label="Potential" value={summary.potential} tone="amber" /><Metric label="Watch" value={summary.watch} tone="cyan" /><Metric label="No trade" value={summary.noTrade} tone="rose" /><Metric label="Data unavailable" value={summary.dataUnavailable} tone="slate" /></div></section>; }

function DiscoveryCard({ item, online, onInspect, onPaper }: { item: DiscoveryItem; online: boolean; onInspect: () => void; onPaper: () => void }) { const qualified = item.status === "QUALIFIED" && item.paperTradeEligible; const Icon = item.status === "QUALIFIED" ? CircleCheck : item.status === "DATA UNAVAILABLE" ? CircleAlert : item.status === "NO TRADE" ? CircleAlert : Clock3; return <article className={`overflow-hidden rounded-2xl border ${item.status === "QUALIFIED" ? "border-emerald-300/20 bg-[#09111f]" : "border-white/[.08] bg-slate-950/55"}`}><div className="flex flex-wrap items-start justify-between gap-3 border-b border-white/[.06] px-5 py-4"><div className="flex items-start gap-3"><span className="mt-0.5 font-mono text-xs text-slate-500">{item.rank ? String(item.rank).padStart(2, "0") : "—"}</span><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold">{item.symbol}</h3><span className={`rounded-full border px-2 py-1 text-[10px] font-semibold tracking-wide ${tone[item.status]}`}>{item.status}</span><span className="rounded-full border border-white/[.08] px-2 py-1 text-[10px] text-slate-400">{item.maturity}</span><span className="rounded-full border border-white/[.08] px-2 py-1 text-[10px] text-slate-400">{item.direction}</span></div><p className="mt-1 text-[11px] text-slate-500">Opportunity {item.opportunityScore ?? "UNAVAILABLE"}/100 · {item.provider ?? "UNAVAILABLE"} · {time(item.dataTimestamp)} · {item.timeframeAgreement.label}</p></div></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={onInspect} className="border-white/[.1] text-slate-300"><Eye className="mr-1.5 h-3.5 w-3.5" />Asset Intelligence</Button>{qualified ? <Button size="sm" onClick={onPaper} disabled={!online} className="bg-emerald-300 text-slate-950 hover:bg-emerald-200 disabled:bg-slate-600"><ArrowUpRight className="mr-1.5 h-3.5 w-3.5" />Paper {item.direction}</Button> : null}</div></div><div className="grid gap-4 p-5 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-xl border border-white/[.07] bg-white/[.02] p-4"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-cyan-200" /><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-cyan-200">Why this status</p></div><p className="mt-2 text-sm leading-6 text-slate-200">{item.exactReason}</p>{item.whyInteresting.length ? <ul className="mt-3 space-y-1.5 text-xs leading-5 text-slate-300">{item.whyInteresting.map(reason => <li key={reason}>• {reason}</li>)}</ul> : null}{item.dataReason ? <p className="mt-3 rounded-lg border border-slate-400/15 bg-black/10 p-3 text-xs leading-5 text-slate-400">{item.dataReason}</p> : null}</section>{qualified ? <QualifiedLevels item={item} /> : <UpgradeConditions item={item} />}</div></article>; }

function QualifiedLevels({ item }: { item: DiscoveryItem }) { return <section className="rounded-xl border border-emerald-300/15 bg-emerald-300/[.035] p-4"><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-emerald-200">Validated trade plan</p><p className="mt-2 text-xs leading-5 text-slate-400">These existing technical levels are shown only for a qualified plan. Paper Trading remains simulated and requires explicit confirmation.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{item.sourcePlan.entryZone ? <Metric label="Preferred entry" value={money.format(item.sourcePlan.entryZone.preferred)} tone="emerald" /> : null}{item.sourcePlan.stop ? <Metric label="Stop" value={money.format(item.sourcePlan.stop.price)} tone="rose" /> : null}{item.sourcePlan.targets.map(target => <Metric key={target.label} label={target.label} value={money.format(target.price)} tone="emerald" />)}{item.sourcePlan.rewardRisk !== null ? <Metric label="First R:R" value={`${item.sourcePlan.rewardRisk}:1`} tone="cyan" /> : null}</div></section>; }

function UpgradeConditions({ item }: { item: DiscoveryItem }) { return <section className="rounded-xl border border-amber-300/15 bg-amber-300/[.035] p-4"><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-amber-200">What would change this setup?</p><p className="mt-2 text-xs leading-5 text-slate-300">{item.status === "POTENTIAL" || item.status === "WATCH" ? "Monitoring evidence only — not a trade instruction." : "This state is not eligible for an entry."}</p>{item.whatWouldChange.length ? <ul className="mt-3 space-y-1.5 text-xs leading-5 text-slate-300">{item.whatWouldChange.map(reason => <li key={reason}>• {reason}</li>)}</ul> : null}{item.conditionalEntry ? <div className="mt-3 rounded-lg border border-cyan-300/15 bg-cyan-300/[.035] p-3"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-cyan-200">Conditional entry</p><p className="mt-1 text-xs leading-5 text-cyan-100/85">{item.conditionalEntry}</p></div> : null}</section>; }

function Metric({ label, value, tone }: { label: string; value: string | number; tone: "emerald" | "amber" | "cyan" | "rose" | "slate" }) { const color = tone === "emerald" ? "text-emerald-200" : tone === "amber" ? "text-amber-200" : tone === "cyan" ? "text-cyan-200" : tone === "rose" ? "text-rose-200" : "text-slate-300"; return <div className="rounded-lg border border-white/[.07] bg-black/10 px-3 py-2"><span className="block text-[9px] font-semibold uppercase tracking-[.13em] text-slate-500">{label}</span><strong className={`mt-1 block break-words font-mono text-sm ${color}`}>{value}</strong></div>; }
function Loading() { return <div className="grid min-h-[40vh] place-items-center"><div className="text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-cyan-200" /><p className="mt-3 text-sm text-slate-400">Interpreting validated Swing evidence…</p></div></div>; }
function ErrorPanel({ detail }: { detail: string }) { return <div className="rounded-xl border border-rose-300/25 bg-rose-300/[.06] p-4 text-sm text-rose-100"><strong>Opportunity Discovery unavailable.</strong><p className="mt-1 text-xs text-rose-100/75">{detail}</p></div>; }
function Empty() { return <div className="rounded-2xl border border-dashed border-white/[.12] p-8 text-center text-sm text-slate-400"><Target className="mx-auto h-5 w-5 text-slate-600" /><p className="mt-3 font-medium text-slate-300">No current opportunities in this filter</p><p className="mt-1 text-xs leading-5">The workspace will not manufacture a setup when validated Swing evidence does not support one.</p></div>; }
