import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import type { ScannerRow } from "@shared/crypto";
import { ArrowDownRight, ArrowUpRight, BadgeDollarSign, ChevronRight, Loader2, ShieldCheck, WalletCards } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type PaperTradingPanelProps = { open: boolean; onOpenChange: (open: boolean) => void; asset: ScannerRow | null };
type Snapshot = { scannerGeneratedAt?: number; asset?: { symbol?: string; name?: string; sector?: string; price?: number }; opportunity?: { score?: number; confidence?: number; technicalScore?: number; setupType?: string; reasons?: Array<{ label: string; score: number; maxScore: number; detail: string }> }; marketRegime?: { classification?: string; score?: number } | null; observation?: { timestamp?: number; entryPrice?: number; stopLoss?: number; target?: number; exactScoringComponents?: Array<{ label: string; score: number; maxScore: number; detail: string }>; missingConditions?: string[] } };
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 });

export function PaperTradingPanel({ open, onOpenChange, asset }: PaperTradingPanelProps) {
  const { user, loading } = useAuth();
  const utils = trpc.useUtils();
  const [side, setSide] = useState<"long" | "short">("long");
  const [riskPercent, setRiskPercent] = useState(1);
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const portfolio = trpc.crypto.paperPortfolio.useQuery(undefined, { enabled: open && Boolean(user) });
  const openTrade = trpc.crypto.openPaperTrade.useMutation({
    onSuccess: async result => {
      await Promise.all([utils.crypto.paperPortfolio.invalidate(), utils.crypto.scanner.invalidate()]);
      toast.success("Paper trade recorded", { description: `Entry ${result.entryPrice}; stop ${result.stopLoss}; 2R target ${result.takeProfit}. The entry snapshot is now immutable.` });
    },
    onError: error => toast.error("Paper trade was not recorded", { description: error.message }),
  });
  const closeTrade = trpc.crypto.closePaperTrade.useMutation({
    onSuccess: async result => {
      await utils.crypto.paperPortfolio.invalidate();
      toast.success("Paper trade closed", { description: `Exit ${result.exitPrice}; realized P/L ${money.format(result.realizedPnl)}.` });
    },
    onError: error => toast.error("Paper trade was not closed", { description: error.message }),
  });
  const create = () => { if (asset?.score) openTrade.mutate({ assetId: asset.asset.id, side, riskPercent }); };
  return <><Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-4xl border-white/[.1] bg-[#0b1220] p-0 text-slate-100 sm:rounded-xl"><DialogHeader className="border-b border-white/[.07] px-6 py-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-300/[.12] text-emerald-200"><WalletCards className="h-4 w-4" /></span><div><DialogTitle className="text-base">Paper trading lab</DialogTitle><DialogDescription className="mt-1 text-xs text-slate-500">Simulated positions retain the exact immutable score, signal reasons, indicator state, regime, provider, and timestamp present at entry.</DialogDescription></div></div></DialogHeader>{loading ? <Loading /> : !user ? <SignIn /> : <ScrollArea className="h-[min(72vh,650px)]"><div className="space-y-6 p-6"><LiveSignal asset={asset} side={side} setSide={setSide} riskPercent={riskPercent} setRiskPercent={setRiskPercent} onCreate={create} pending={openTrade.isPending} /><PortfolioView portfolio={portfolio.data} loading={portfolio.isLoading} onClose={tradeId => closeTrade.mutate({ tradeId })} closing={closeTrade.isPending} onSnapshot={value => setSnapshot(value as Snapshot)} /></div></ScrollArea>}</DialogContent></Dialog><SnapshotDialog snapshot={snapshot} onOpenChange={open => { if (!open) setSnapshot(null); }} /></>;
}

function LiveSignal({ asset, side, setSide, riskPercent, setRiskPercent, onCreate, pending }: { asset: ScannerRow | null; side: "long" | "short"; setSide: (side: "long" | "short") => void; riskPercent: number; setRiskPercent: (value: number) => void; onCreate: () => void; pending: boolean }) {
  if (!asset?.score) return <section className="rounded-xl border border-dashed border-white/[.1] p-5 text-center"><p className="text-sm text-slate-300">Select an opportunity from Asset Intelligence or the scanner to simulate it.</p><p className="mt-1 text-xs text-slate-500">No generic or synthetic paper-trade form is provided.</p></section>;
  return <section className="rounded-xl border border-emerald-300/15 bg-emerald-300/[.04] p-4"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><span className="text-[10px] font-semibold uppercase tracking-[.17em] text-emerald-200">Live signal selected</span><h3 className="mt-1 text-lg font-semibold">{asset.asset.symbol} · {asset.score.setupType}</h3><p className="mt-1 text-xs leading-5 text-slate-400">Opportunity {asset.score.score}/100 · Confidence {asset.score.confidence}/100 · Current price {asset.asset.price === null ? "Unavailable" : money.format(asset.asset.price)}</p></div><span className="flex items-center gap-1.5 rounded-full border border-emerald-300/20 px-2.5 py-1 text-[10px] text-emerald-200"><ShieldCheck className="h-3 w-3" />Immutable snapshot on entry</span></div><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_1fr_125px]"><div className="flex rounded-lg border border-white/[.08] bg-black/10 p-1"><button onClick={() => setSide("long")} className={`flex-1 rounded-md py-2 text-xs font-medium ${side === "long" ? "bg-emerald-300/15 text-emerald-200" : "text-slate-500"}`}><ArrowUpRight className="mr-1 inline h-3.5 w-3.5" />Long</button><button onClick={() => setSide("short")} className={`flex-1 rounded-md py-2 text-xs font-medium ${side === "short" ? "bg-rose-300/15 text-rose-200" : "text-slate-500"}`}><ArrowDownRight className="mr-1 inline h-3.5 w-3.5" />Short</button></div><label className="flex items-center justify-between rounded-lg border border-white/[.08] bg-black/10 px-3 text-xs text-slate-400">Risk <input type="number" min="0.1" max="5" step="0.1" value={riskPercent} onChange={event => setRiskPercent(Number(event.target.value))} className="w-12 bg-transparent text-right font-mono text-emerald-100 outline-none" /><span>%</span></label><Button onClick={onCreate} disabled={pending || asset.asset.price === null} className="bg-emerald-300 text-xs text-slate-950 hover:bg-emerald-200">{pending ? <Loader2 className="mr-2 h-3.5 w-3.5 animate-spin" /> : <BadgeDollarSign className="mr-2 h-3.5 w-3.5" />}Record trade</Button></div></section>;
}

function PortfolioView({ portfolio, loading, onClose, closing, onSnapshot }: { portfolio: { metrics: { currentEquity: number; realizedPnl: number; unrealizedPnl: number; winRate: number | null; maxDrawdown: number; profitFactor: number | null; sharpeRatio: number | null; tradeCount: number }; trades: Array<{ id: number; side: string; assetId: string; status: string; entryPrice: number; realizedPnl: number | null; immutableEntrySnapshot: unknown }> } | undefined; loading: boolean; onClose: (tradeId: number) => void; closing: boolean; onSnapshot: (snapshot: unknown) => void }) {
  return <section><div className="mb-3"><span className="text-[10px] font-semibold uppercase tracking-[.17em] text-emerald-200">Portfolio</span><h3 className="mt-1 text-sm font-semibold">Current simulated performance</h3></div>{loading ? <Loading /> : portfolio ? <><div className="grid gap-2 sm:grid-cols-4"><Metric label="Equity" value={money.format(portfolio.metrics.currentEquity)} /><Metric label="Realized P/L" value={money.format(portfolio.metrics.realizedPnl)} /><Metric label="Unrealized P/L" value={money.format(portfolio.metrics.unrealizedPnl)} /><Metric label="Win rate" value={portfolio.metrics.winRate === null ? "—" : `${portfolio.metrics.winRate}%`} /></div><div className="mt-3 grid gap-2 sm:grid-cols-4"><Metric label="Max drawdown" value={`${portfolio.metrics.maxDrawdown}%`} /><Metric label="Profit factor" value={portfolio.metrics.profitFactor === null ? "—" : String(portfolio.metrics.profitFactor)} /><Metric label="Sharpe" value={portfolio.metrics.sharpeRatio === null ? "—" : String(portfolio.metrics.sharpeRatio)} /><Metric label="Trades" value={String(portfolio.metrics.tradeCount)} /></div><div className="mt-5 overflow-hidden rounded-xl border border-white/[.07]"><div className="grid grid-cols-[minmax(120px,1fr)_72px_80px_120px] gap-2 border-b border-white/[.07] bg-white/[.025] px-4 py-2 text-[9px] font-semibold uppercase tracking-[.14em] text-slate-500"><span>Position</span><span>Status</span><span>Entry</span><span /></div>{portfolio.trades.length ? portfolio.trades.map(trade => <div key={trade.id} className="grid grid-cols-[minmax(120px,1fr)_72px_80px_120px] items-center gap-2 border-b border-white/[.055] px-4 py-3 text-xs last:border-0"><span><span className="block font-medium text-slate-200">{trade.side.toUpperCase()} · {trade.assetId}</span><span className="mt-0.5 block text-[10px] text-slate-500">Immutable entry snapshot retained</span></span><span className={trade.status === "open" ? "text-cyan-200" : "text-slate-400"}>{trade.status}</span><span className="font-mono text-slate-300">{trade.entryPrice}</span><span className="flex items-center justify-end gap-1"><Button variant="ghost" size="sm" onClick={() => onSnapshot(trade.immutableEntrySnapshot)} className="h-7 px-2 text-[10px] text-cyan-200 hover:bg-cyan-300/[.08] hover:text-cyan-100">Why?<ChevronRight className="ml-1 h-3 w-3" /></Button>{trade.status === "open" ? <Button variant="ghost" size="sm" onClick={() => onClose(trade.id)} disabled={closing} className="h-7 px-2 text-[10px] text-rose-200 hover:bg-rose-300/[.08] hover:text-rose-100">Close</Button> : <span className="font-mono text-[10px] text-slate-400">{trade.realizedPnl === null ? "—" : money.format(trade.realizedPnl)}</span>}</span></div>) : <div className="p-6 text-center text-xs text-slate-500">No paper positions have been recorded.</div>}</div></> : null}</section>;
}

function SnapshotDialog({ snapshot, onOpenChange }: { snapshot: Snapshot | null; onOpenChange: (open: boolean) => void }) { const reasons = snapshot?.observation?.exactScoringComponents ?? snapshot?.opportunity?.reasons ?? []; return <Dialog open={Boolean(snapshot)} onOpenChange={onOpenChange}><DialogContent className="max-w-3xl border-white/[.1] bg-[#0b1220] text-slate-100"><DialogHeader><DialogTitle>Why this paper trade was opened</DialogTitle><DialogDescription>Immutable entry evidence retained at the time the simulated position was recorded; it is never reconstructed from current data.</DialogDescription></DialogHeader>{snapshot ? <div className="space-y-4"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Score" value={snapshot.opportunity?.score === undefined ? "UNAVAILABLE" : `${snapshot.opportunity.score}/100`} /><Metric label="Confidence" value={snapshot.opportunity?.confidence === undefined ? "UNAVAILABLE" : `${snapshot.opportunity.confidence}/100`} /><Metric label="Setup" value={snapshot.opportunity?.setupType ?? "UNAVAILABLE"} /><Metric label="Regime" value={snapshot.marketRegime?.classification ?? "UNAVAILABLE"} /></div><div className="grid gap-2 sm:grid-cols-3"><Metric label="Entry" value={snapshot.observation?.entryPrice === undefined ? "UNAVAILABLE" : money.format(snapshot.observation.entryPrice)} /><Metric label="Stop" value={snapshot.observation?.stopLoss === undefined ? "UNAVAILABLE" : money.format(snapshot.observation.stopLoss)} /><Metric label="Target" value={snapshot.observation?.target === undefined ? "UNAVAILABLE" : money.format(snapshot.observation.target)} /></div><section className="rounded-xl border border-white/[.07] bg-white/[.02] p-4"><span className="text-[10px] font-semibold uppercase tracking-[.15em] text-emerald-200">Stored score evidence</span><div className="mt-3 space-y-2">{reasons.length ? reasons.map(reason => <div key={reason.label} className="rounded-lg border border-white/[.06] bg-black/10 px-3 py-2.5"><div className="flex justify-between gap-3"><span className="text-xs font-medium text-slate-200">{reason.label}</span><span className="font-mono text-xs text-emerald-200">{reason.score}/{reason.maxScore}</span></div><p className="mt-1 text-[11px] leading-4 text-slate-500">{reason.detail}</p></div>) : <p className="text-xs text-slate-500">UNAVAILABLE — no score evidence was stored on this legacy trade.</p>}</div></section>{snapshot.observation?.missingConditions?.length ? <section className="rounded-xl border border-amber-300/15 bg-amber-300/[.035] p-4"><span className="text-[10px] font-semibold uppercase tracking-[.15em] text-amber-200">Stored missing conditions</span><ul className="mt-2 space-y-1 text-xs text-amber-100/75">{snapshot.observation.missingConditions.map(item => <li key={item}>{item}</li>)}</ul></section> : null}</div> : null}</DialogContent></Dialog>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-white/[.07] bg-white/[.02] px-3 py-2.5"><span className="block text-[9px] font-semibold uppercase tracking-[.13em] text-slate-500">{label}</span><span className="mt-1 block truncate font-mono text-sm text-slate-100">{value}</span></div>; }
function Loading() { return <div className="grid min-h-40 place-items-center"><Loader2 className="h-5 w-5 animate-spin text-emerald-300" /></div>; }
function SignIn() { return <div className="grid min-h-72 place-items-center px-6 text-center"><div><h3 className="text-sm font-semibold">Sign in to start a paper portfolio</h3><p className="mx-auto mt-2 max-w-sm text-xs leading-5 text-slate-500">No simulated trade is created until it is explicitly recorded under your account.</p><Button onClick={() => startLogin()} className="mt-5 bg-emerald-300 text-slate-950 hover:bg-emerald-200">Sign in to paper trade</Button></div></div>; }
