import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { usePwaStatus } from "@/pwa/PwaStatus";
import { ArrowLeft, ArrowDownRight, ArrowUpRight, CircleAlert, CircleCheck, CircleX, Eye, Loader2, ShieldCheck, Target } from "lucide-react";

type Mode = "SCALP" | "SWING";
type Plan = {
  assetId: string; symbol: string; mode: Mode; actionable: boolean; availability: "LIVE" | "STALE" | "UNAVAILABLE"; minimumValidatedTimeframe: string; direction: "LONG" | "SHORT" | "NO TRADE"; setupType: string; expectedHorizon: string; dataTimestamp: number | null; provider: string | null; opportunityScore: number | null; regimeScore: number | null; regimeClassification: string | null; marketContext: string; tradeSetupQuality: number | null; entryZone: { low: number; high: number; preferred: number; reason: string } | null; stop: { price: number; reason: string } | null; invalidation: { price: number; reason: string } | null; targets: Array<{ label: string; price: number; reason: string; priority: string }>; rewardRisk: number | null; evidence: string[]; risks: string[]; unavailable: string[];
};

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 5 });
const timestamp = (value: number | null) => value ? new Date(value).toLocaleString() : "UNAVAILABLE";
const directionTone = (direction: Plan["direction"]) => direction === "LONG" ? "text-emerald-200 border-emerald-300/25 bg-emerald-300/[.07]" : direction === "SHORT" ? "text-rose-200 border-rose-300/25 bg-rose-300/[.07]" : "text-slate-300 border-slate-500/25 bg-slate-500/[.07]";

export function TradeSetupWorkspace({ mode, onBack, onInspectAsset, onPaperTrade }: { mode: Mode; onBack: () => void; onInspectAsset: (assetId: string) => void; onPaperTrade: (assetId: string, mode: Mode) => void }) {
  const { online } = usePwaStatus();
  const setups = trpc.crypto.tradeSetups.useQuery({ mode }, { staleTime: 30_000, refetchOnWindowFocus: false, enabled: online });
  const data = setups.data as { generatedAt: number; lowerTimeframeDataReady: boolean; minimumValidatedTimeframe: string; marketRegime: { classification: string; score: number } | null; setups: Plan[] } | undefined;
  const title = mode === "SCALP" ? "Scalping" : "Swing";
  return <div className="space-y-6 pb-20"><header className="flex flex-wrap items-start justify-between gap-4 border-b border-white/[.07] pb-5"><div className="flex items-start gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${mode === "SCALP" ? "bg-cyan-300/[.12] text-cyan-200" : "bg-violet-300/[.12] text-violet-200"}`}><Target className="h-5 w-5" /></span><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-slate-500">Validated research intelligence</p><h2 className="mt-1 text-xl font-semibold tracking-tight">{title}</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-slate-400">Discover → explain → plan → monitor. Setup Quality is a separate, explainable presentation layer; it does not alter Opportunity Score or Regime Score.</p></div></div><Button variant="outline" onClick={onBack} className="border-white/[.1] bg-white/[.025] text-slate-200"><ArrowLeft className="mr-2 h-4 w-4" />Back to Dashboard</Button></header>
    <section className="grid gap-3 sm:grid-cols-3"><StatusCard label="Minimum execution data" value={data?.minimumValidatedTimeframe ?? "Current minimum validated timeframe: 15M"} tone="cyan" /><StatusCard label="Lower timeframe capability" value={data?.lowerTimeframeDataReady ? "READY" : "NOT ENABLED — 1M/3M/5M"} tone="amber" /><StatusCard label="Market context" value={data?.marketRegime ? `${data.marketRegime.classification} · ${data.marketRegime.score}/100` : "UNAVAILABLE"} tone="violet" /></section>
    {!online ? <div role="status" className="rounded-xl border border-amber-300/25 bg-amber-300/[.06] p-4 text-xs text-amber-100"><strong>OFFLINE · READ ONLY.</strong> New setup plans require current validated market inputs. No Paper Trade can be opened while offline.</div> : null}
    {setups.isLoading ? <div className="grid min-h-[40vh] place-items-center"><div className="text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-cyan-200" /><p className="mt-3 text-sm text-slate-400">Validating multi-timeframe setup inputs…</p></div></div> : setups.error ? <div className="rounded-xl border border-rose-300/25 bg-rose-300/[.06] p-4 text-sm text-rose-100"><strong>Setup intelligence unavailable.</strong><p className="mt-1 text-xs text-rose-100/75">{setups.error.message}</p></div> : <section className="space-y-4">{data?.setups.map((plan, index) => <SetupCard key={`${plan.mode}-${plan.assetId}`} plan={plan} rank={index + 1} online={online} onInspect={() => onInspectAsset(plan.assetId)} onPaperTrade={() => onPaperTrade(plan.assetId, mode)} />) ?? <Empty />}</section>}
  </div>;
}

function SetupCard({ plan, rank, online, onInspect, onPaperTrade }: { plan: Plan; rank: number; online: boolean; onInspect: () => void; onPaperTrade: () => void }) {
  const actionable = plan.actionable && plan.entryZone && plan.stop && plan.invalidation;
  return <article className={`overflow-hidden rounded-2xl border ${actionable ? "border-cyan-300/18 bg-[#09111f]" : "border-slate-500/20 bg-slate-950/55"}`}><div className="flex flex-wrap items-start justify-between gap-3 border-b border-white/[.06] px-5 py-4"><div className="flex items-center gap-3"><span className="font-mono text-xs text-slate-500">{String(rank).padStart(2, "0")}</span><div><div className="flex items-center gap-2"><h3 className="text-lg font-semibold">{plan.symbol}</h3><span className={`rounded-full border px-2 py-1 text-[10px] font-semibold tracking-wide ${directionTone(plan.direction)}`}>{plan.direction}</span><span className="rounded-full border border-white/[.08] px-2 py-1 text-[10px] text-slate-400">{plan.setupType}</span></div><p className="mt-1 text-[11px] text-slate-500">{plan.provider ?? "UNAVAILABLE"} · {timestamp(plan.dataTimestamp)} · {plan.mode === "SCALP" ? "15M / 1H / 4H" : "1H / 4H / 1D"}</p></div></div><div className="flex items-center gap-2"><Button size="sm" variant="outline" onClick={onInspect} className="border-white/[.1] text-slate-300"><Eye className="mr-1.5 h-3.5 w-3.5" />Asset Intelligence</Button>{actionable ? <Button size="sm" onClick={onPaperTrade} disabled={!online} className="bg-emerald-300 text-slate-950 hover:bg-emerald-200 disabled:bg-slate-600"><ArrowUpRight className="mr-1.5 h-3.5 w-3.5" />Paper {plan.direction}</Button> : null}</div></div>
    {actionable ? <div className="grid gap-4 p-5 xl:grid-cols-[1.1fr_.9fr]"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Level label="Entry zone" value={`${money.format(plan.entryZone!.low)} – ${money.format(plan.entryZone!.high)}`} note={plan.entryZone!.reason} /><Level label="Preferred entry" value={money.format(plan.entryZone!.preferred)} note="Execution-timeframe technical level" /><Level label="Stop / invalidation" value={money.format(plan.stop!.price)} note={plan.stop!.reason} tone="risk" /><Level label="Expected R:R" value={plan.rewardRisk === null ? "UNAVAILABLE" : `${plan.rewardRisk}:1`} note="First technical target relative to structural stop" tone="positive" />{plan.targets.map(target => <Level key={target.label} label={target.label} value={money.format(target.price)} note={target.reason} tone="positive" />)}</div><Evidence plan={plan} /></div> : <div className="p-5"><div className="flex gap-3"><CircleAlert className="mt-0.5 h-5 w-5 shrink-0 text-slate-400" /><div><p className="font-semibold text-slate-200">NO TRADE · {plan.availability}</p><p className="mt-1 text-sm leading-6 text-slate-400">{plan.unavailable.join(" ") || "Required validated setup inputs are unavailable."}</p><p className="mt-2 text-xs text-slate-500">No entry, target, stop, probability, or trade action is fabricated when technical derivation fails.</p></div></div></div>}</article>;
}

function Evidence({ plan }: { plan: Plan }) { return <div className="grid gap-3 sm:grid-cols-2"><section className="rounded-xl border border-emerald-300/15 bg-emerald-300/[.035] p-4"><div className="flex items-center gap-2"><CircleCheck className="h-4 w-4 text-emerald-300" /><h4 className="text-[10px] font-semibold uppercase tracking-[.15em] text-emerald-200">Why this setup</h4></div><p className="mt-2 text-sm font-semibold text-slate-100">Setup Quality {plan.tradeSetupQuality ?? "UNAVAILABLE"}/100</p><ul className="mt-3 space-y-1.5 text-xs leading-5 text-slate-300">{plan.evidence.slice(0, 5).map(item => <li key={item}>• {item}</li>)}</ul></section><section className="rounded-xl border border-amber-300/15 bg-amber-300/[.035] p-4"><div className="flex items-center gap-2"><CircleX className="h-4 w-4 text-amber-300" /><h4 className="text-[10px] font-semibold uppercase tracking-[.15em] text-amber-200">Risk factors</h4></div><p className="mt-2 text-sm font-semibold text-slate-100">Opportunity {plan.opportunityScore ?? "UNAVAILABLE"} · Regime {plan.regimeScore ?? "UNAVAILABLE"}</p><ul className="mt-3 space-y-1.5 text-xs leading-5 text-slate-300">{plan.risks.length ? plan.risks.slice(0, 5).map(item => <li key={item}>• {item}</li>) : <li>• No negative technical component is currently recorded.</li>}</ul></section></div>; }
function Level({ label, value, note, tone = "neutral" }: { label: string; value: string; note: string; tone?: "neutral" | "positive" | "risk" }) { const color = tone === "positive" ? "text-emerald-200" : tone === "risk" ? "text-rose-200" : "text-cyan-100"; return <div className="rounded-xl border border-white/[.07] bg-white/[.02] p-3"><span className="block text-[9px] font-semibold uppercase tracking-[.13em] text-slate-500">{label}</span><strong className={`mt-1 block break-words font-mono text-sm ${color}`}>{value}</strong><p className="mt-2 text-[10px] leading-4 text-slate-500">{note}</p></div>; }
function StatusCard({ label, value, tone }: { label: string; value: string; tone: "cyan" | "amber" | "violet" }) { const color = tone === "cyan" ? "text-cyan-100 border-cyan-300/15 bg-cyan-300/[.035]" : tone === "amber" ? "text-amber-100 border-amber-300/15 bg-amber-300/[.035]" : "text-violet-100 border-violet-300/15 bg-violet-300/[.035]"; return <div className={`rounded-xl border p-4 ${color}`}><span className="text-[9px] font-semibold uppercase tracking-[.14em] opacity-70">{label}</span><p className="mt-2 text-xs font-medium">{value}</p></div>; }
function Empty() { return <div className="rounded-2xl border border-dashed border-white/[.12] p-8 text-center text-sm text-slate-400">No setup response is available. The workspace will not construct a fallback opportunity.</div>; }
