import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { usePwaStatus } from "@/pwa/PwaStatus";
import { ArrowLeft, ArrowUpRight, CircleAlert, CircleCheck, CircleX, Clock3, Eye, Loader2, Target } from "lucide-react";

type Mode = "SCALP" | "SWING";
type Condition = { key: string; label: string; status: "PASSED" | "FAILED" | "UNAVAILABLE" | "STALE"; actual: string; required: string; detail: string };
type DiagnosticSummary = { evaluatedAssets: number; noTradeAssets: number; byCondition: Array<{ key: string; label: string; passed: number; failed: number; unavailable: number; stale: number }>; topNoTradeReasons: Array<{ key: string; label: string; count: number; status: "FAILED" | "UNAVAILABLE" | "STALE" }>; classification: { lackOfMarketSetups: number; missingData: number; staleData: number; existingSetupRequirement: number } };
type ProviderHealth = { provider: "Binance Futures" | "Kraken Spot" | "CoinGecko"; status: "LIVE" | "PARTIAL" | "UNAVAILABLE"; lastSuccessfulAt: number | null; lastFailureAt: number | null; failureClassification: string | null; supportedTimeframes: string[]; validatedSymbols: string[]; note: string };
type DataBundle = { provider: string | null; state: string | null; coherent: boolean; eligibleForScoring: boolean; statusMessage: string; timeframes: Array<{ timeframe: string; provider: string | null; state: string; status: "live" | "stale" | "unavailable"; fetchedAt: number | null; candleCount: number; eligibleForScoring: boolean; message: string | null; errorClass: string | null }> };
type Plan = {
  assetId: string; symbol: string; mode: Mode; actionable: boolean; presentationStatus: "QUALIFIED" | "WATCH" | "NO TRADE"; rank: number | null; watch: { missing: string[]; wouldQualifyWhen: string[] } | null; availability: "LIVE" | "STALE" | "UNAVAILABLE"; direction: "LONG" | "SHORT" | "NO TRADE"; setupType: string; expectedHorizon: string; dataTimestamp: number | null; provider: string | null; dataBundle: DataBundle; opportunityScore: number | null; regimeScore: number | null; marketContext: string; entryZone: { low: number; high: number; preferred: number; reason: string } | null; stop: { price: number; reason: string } | null; invalidation: { price: number; reason: string } | null; targets: Array<{ label: string; price: number; reason: string; priority: string }>; rewardRisk: number | null; evidence: string[]; risks: string[]; unavailable: string[]; diagnostics: Condition[];
};
type SetupResponse = { generatedAt: number; lowerTimeframeDataReady: boolean; minimumValidatedTimeframe: string; marketRegime: { classification: string; score: number } | null; providerHealth: ProviderHealth[]; diagnostics: DiagnosticSummary; setups: Plan[] };

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 5 });
const timestamp = (value: number | null) => value ? new Date(value).toLocaleString() : "UNAVAILABLE";
const directionTone = (direction: Plan["direction"]) => direction === "LONG" ? "text-emerald-200 border-emerald-300/25 bg-emerald-300/[.07]" : direction === "SHORT" ? "text-rose-200 border-rose-300/25 bg-rose-300/[.07]" : "text-slate-300 border-slate-500/25 bg-slate-500/[.07]";

export function TradeSetupWorkspace({ mode, onBack, onInspectAsset, onPaperTrade }: { mode: Mode; onBack: () => void; onInspectAsset: (assetId: string) => void; onPaperTrade: (assetId: string, mode: Mode) => void }) {
  const { online } = usePwaStatus();
  const setups = trpc.crypto.tradeSetups.useQuery({ mode }, { staleTime: 30_000, refetchOnWindowFocus: false, enabled: online });
  const data = setups.data as SetupResponse | undefined;
  const title = mode === "SCALP" ? "Scalping" : "Swing";
  return <div className="space-y-6 pb-20">
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-white/[.07] pb-5">
      <div className="flex items-start gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${mode === "SCALP" ? "bg-cyan-300/[.12] text-cyan-200" : "bg-violet-300/[.12] text-violet-200"}`}><Target className="h-5 w-5" /></span><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-slate-500">Validated research intelligence</p><h2 className="mt-1 text-xl font-semibold tracking-tight">{title}</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-slate-400">Find → explain → plan → monitor. Qualification, Watch, and No Trade are descriptive states built from existing validated inputs; they do not change Opportunity or Regime scoring.</p></div></div>
      <Button variant="outline" onClick={onBack} className="border-white/[.1] bg-white/[.025] text-slate-200"><ArrowLeft className="mr-2 h-4 w-4" />Back to Dashboard</Button>
    </header>
    <section className="grid gap-3 sm:grid-cols-3"><StatusCard label="Validated timeframes" value={mode === "SCALP" ? "15M · 1H · 4H" : "1H · 4H · 1D"} tone="cyan" /><StatusCard label="Lower timeframe capability" value={data?.lowerTimeframeDataReady ? "READY" : "1M / 3M / 5M — UNAVAILABLE"} tone="amber" /><StatusCard label="Market context" value={data?.marketRegime ? `${data.marketRegime.classification} · ${data.marketRegime.score}/100` : "UNAVAILABLE"} tone="violet" /></section>
    {data?.providerHealth ? <ProviderHealthPanel providers={data.providerHealth} /> : null}
    {!online ? <div role="status" className="rounded-xl border border-amber-300/25 bg-amber-300/[.06] p-4 text-xs text-amber-100"><strong>OFFLINE · READ ONLY.</strong> Current setup refresh and Paper Trading actions remain unavailable until a live connection is restored.</div> : null}
    {setups.isLoading ? <Loading /> : setups.error ? <ErrorPanel detail={setups.error.message} /> : data ? <section className="space-y-4"><SetupOverview summary={data.diagnostics} plans={data.setups} />{data.setups.map((plan, index) => <SetupCard key={`${plan.mode}-${plan.assetId}`} plan={plan} ordinal={plan.rank ?? index + 1} online={online} onInspect={() => onInspectAsset(plan.assetId)} onPaperTrade={() => onPaperTrade(plan.assetId, mode)} />)}</section> : <Empty />}
  </div>;
}

function SetupCard({ plan, ordinal, online, onInspect, onPaperTrade }: { plan: Plan; ordinal: number; online: boolean; onInspect: () => void; onPaperTrade: () => void }) {
  const qualified = plan.presentationStatus === "QUALIFIED" && plan.actionable && plan.entryZone && plan.stop && plan.invalidation;
  const statusTone = plan.presentationStatus === "QUALIFIED" ? "border-emerald-300/25 bg-emerald-300/[.07] text-emerald-100" : plan.presentationStatus === "WATCH" ? "border-amber-300/25 bg-amber-300/[.07] text-amber-100" : "border-slate-500/25 bg-slate-500/[.07] text-slate-300";
  const targetRr = (target: Plan["targets"][number]) => !plan.entryZone || !plan.stop ? null : Math.abs(target.price - plan.entryZone!.preferred) / Math.max(Math.abs(plan.entryZone!.preferred - plan.stop!.price), Number.EPSILON);
  return <article className={`overflow-hidden rounded-2xl border ${qualified ? "border-cyan-300/18 bg-[#09111f]" : plan.presentationStatus === "WATCH" ? "border-amber-300/20 bg-amber-300/[.025]" : "border-slate-500/20 bg-slate-950/55"}`}>
    <div className="flex flex-wrap items-start justify-between gap-3 border-b border-white/[.06] px-5 py-4"><div className="flex items-center gap-3"><span className="font-mono text-xs text-slate-500">{qualified ? String(ordinal).padStart(2, "0") : "—"}</span><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold">{plan.symbol}</h3><span className={`rounded-full border px-2 py-1 text-[10px] font-semibold tracking-wide ${statusTone}`}>{plan.presentationStatus}</span><span className={`rounded-full border px-2 py-1 text-[10px] font-semibold tracking-wide ${directionTone(plan.direction)}`}>{plan.direction}</span><span className="rounded-full border border-white/[.08] px-2 py-1 text-[10px] text-slate-400">{plan.setupType}</span></div><p className="mt-1 text-[11px] text-slate-500">Opportunity {plan.opportunityScore ?? "UNAVAILABLE"}/100 · {plan.provider ?? "UNAVAILABLE"} · {timestamp(plan.dataTimestamp)} · {plan.mode === "SCALP" ? "15M / 1H / 4H" : "1H / 4H / 1D"}</p></div></div><div className="flex items-center gap-2"><Button size="sm" variant="outline" onClick={onInspect} className="border-white/[.1] text-slate-300"><Eye className="mr-1.5 h-3.5 w-3.5" />Asset Intelligence</Button>{qualified ? <Button size="sm" onClick={onPaperTrade} disabled={!online} className="bg-emerald-300 text-slate-950 hover:bg-emerald-200 disabled:bg-slate-600"><ArrowUpRight className="mr-1.5 h-3.5 w-3.5" />Paper {plan.direction}</Button> : null}</div></div>
    <BundleStatus bundle={plan.dataBundle} />
    {qualified ? <div className="grid gap-4 p-5 xl:grid-cols-[1.1fr_.9fr]"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Level label="Entry zone" value={`${money.format(plan.entryZone!.low)} – ${money.format(plan.entryZone!.high)}`} note={plan.entryZone!.reason} /><Level label="Preferred entry" value={money.format(plan.entryZone!.preferred)} note="Execution-timeframe technical level" /><Level label="Stop / invalidation" value={money.format(plan.stop!.price)} note={plan.stop!.reason} tone="risk" />{plan.targets.map(target => <Level key={target.label} label={`${target.label} · ${targetRr(target) === null ? "R:R unavailable" : `R:R ${targetRr(target)!.toFixed(2)}`}`} value={money.format(target.price)} note={target.reason} tone="positive" />)}</div><Evidence plan={plan} /></div> : plan.presentationStatus === "WATCH" ? <WatchEvidence plan={plan} /> : <NoTradeEvidence plan={plan} />}
  </article>;
}

function BundleStatus({ bundle }: { bundle: DataBundle }) { const live = bundle.eligibleForScoring && bundle.coherent; const stateTone = live ? "border-emerald-300/15 bg-emerald-300/[.035]" : bundle.state === "STALE" ? "border-amber-300/15 bg-amber-300/[.035]" : "border-rose-300/15 bg-rose-300/[.035]"; const label = live ? "LIVE & COHERENT" : bundle.state ?? "NO DATA"; return <section className={`border-b border-white/[.06] px-5 py-3 ${stateTone}`} aria-label="Provider data status"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-slate-400">Data status</p><p className="mt-1 text-xs font-semibold text-slate-100">{label} · {bundle.provider ?? "No eligible provider"}</p></div><p className="max-w-xl text-[11px] leading-4 text-slate-400">{bundle.statusMessage}</p></div><div className="mt-3 grid gap-2 sm:grid-cols-3">{bundle.timeframes.map(item => <div key={item.timeframe} className="rounded-lg border border-white/[.08] bg-black/10 p-2"><div className="flex items-center justify-between gap-2"><span className="font-mono text-[11px] text-slate-200">{item.timeframe.toUpperCase()}</span><span className={`text-[9px] font-semibold ${item.eligibleForScoring ? "text-emerald-200" : item.status === "stale" ? "text-amber-200" : "text-rose-200"}`}>{item.state}</span></div><p className="mt-1 truncate text-[10px] text-slate-400">{item.provider ?? "UNAVAILABLE"} · {item.candleCount} closed</p><p className="mt-1 truncate text-[10px] text-slate-500">{item.fetchedAt ? timestamp(item.fetchedAt) : item.errorClass ?? item.message ?? "No response"}</p></div>)}</div></section>; }

function WatchEvidence({ plan }: { plan: Plan }) { return <div className="space-y-4 p-5"><div className="flex gap-3"><Clock3 className="mt-0.5 h-5 w-5 shrink-0 text-amber-200" /><div><p className="font-semibold text-amber-100">WATCH — NOT A TRADE</p><p className="mt-1 text-sm leading-6 text-slate-300">Current data is coherent, but an existing strategy requirement has not passed. No entry, target, stop, or Paper Trading action is created.</p></div></div><div className="grid gap-3 md:grid-cols-2"><TextList title="Missing confirmation" items={plan.watch?.missing ?? []} tone="amber" /><TextList title="Would become eligible when" items={plan.watch?.wouldQualifyWhen ?? []} tone="cyan" /></div><Diagnostics conditions={plan.diagnostics} /></div>; }
function NoTradeEvidence({ plan }: { plan: Plan }) { return <div className="space-y-4 p-5"><div className="flex gap-3"><CircleAlert className="mt-0.5 h-5 w-5 shrink-0 text-slate-400" /><div><p className="font-semibold text-slate-100">NO TRADE — WHY?</p><p className="mt-1 text-sm leading-6 text-slate-400">{plan.unavailable.join(" ") || "The existing setup engine did not confirm a plan from current validated inputs."}</p><p className="mt-2 text-xs text-slate-500">These cards report existing requirements only. No condition was loosened and no level was fabricated.</p></div></div><Diagnostics conditions={plan.diagnostics} /></div>; }
function Diagnostics({ conditions }: { conditions: Condition[] }) { return <div className="grid gap-2 lg:grid-cols-2">{conditions.map(condition => <ConditionCard key={condition.key} condition={condition} />)}</div>; }
function ConditionCard({ condition }: { condition: Condition }) { const tone = condition.status === "PASSED" ? "border-emerald-300/18 bg-emerald-300/[.035]" : condition.status === "FAILED" ? "border-rose-300/18 bg-rose-300/[.035]" : condition.status === "STALE" ? "border-amber-300/18 bg-amber-300/[.035]" : "border-slate-400/15 bg-slate-400/[.035]"; const Icon = condition.status === "PASSED" ? CircleCheck : condition.status === "FAILED" ? CircleX : condition.status === "STALE" ? Clock3 : CircleAlert; const label = condition.status === "PASSED" ? "Passed" : condition.status === "FAILED" ? "Failed" : condition.status === "STALE" ? "Stale" : "Unavailable"; return <section className={`rounded-xl border p-3 ${tone}`}><div className="flex items-start justify-between gap-3"><h4 className="text-xs font-semibold text-slate-100">{condition.label}</h4><span className="flex shrink-0 items-center gap-1 text-[10px] font-semibold uppercase tracking-wide text-slate-300"><Icon className="h-3.5 w-3.5" />{label}</span></div><dl className="mt-3 space-y-2 text-[11px] leading-4"><div><dt className="text-slate-500">Current</dt><dd className="mt-0.5 break-words text-slate-200">{condition.actual}</dd></div><div><dt className="text-slate-500">Required</dt><dd className="mt-0.5 break-words text-slate-300">{condition.required}</dd></div><div><dt className="sr-only">Explanation</dt><dd className="mt-1 border-t border-white/[.07] pt-2 text-slate-400">{condition.detail}</dd></div></dl></section>; }

function SetupOverview({ summary, plans }: { summary: DiagnosticSummary; plans: Plan[] }) { const qualified = plans.filter(plan => plan.presentationStatus === "QUALIFIED").length; const watch = plans.filter(plan => plan.presentationStatus === "WATCH").length; return <section className="rounded-2xl border border-cyan-300/15 bg-cyan-300/[.025] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-cyan-200">Current setup overview</p><h3 className="mt-1 text-sm font-semibold text-slate-100">{summary.evaluatedAssets} assets scanned · {qualified} qualified · {watch} watch · {Math.max(0, summary.noTradeAssets - watch)} no trade</h3></div><p className="max-w-md text-xs leading-5 text-slate-400">Qualified ranking uses the existing Opportunity Score only. Watch and No Trade remain non-actionable until every existing condition passes.</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><Level label="Lack of market setup" value={String(summary.classification.lackOfMarketSetups)} note="Existing direction/structure did not produce a plan" /><Level label="Missing data" value={String(summary.classification.missingData)} note="At least one required input was unavailable" tone="risk" /><Level label="Stale data" value={String(summary.classification.staleData)} note="Existing provider state marked an input stale" /><Level label="Existing setup requirement" value={String(summary.classification.existingSetupRequirement)} note="Valid levels failed the existing R:R minimum" tone="risk" /></div>{summary.topNoTradeReasons.length ? <div className="mt-4 border-t border-white/[.08] pt-3"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-500">Top current NO TRADE reasons</p><div className="mt-2 flex flex-wrap gap-2">{summary.topNoTradeReasons.map(reason => <span key={`${reason.key}-${reason.status}`} className="rounded-full border border-white/[.1] bg-black/10 px-2.5 py-1 text-[11px] text-slate-300">{reason.label}: {reason.count} {reason.status.toLowerCase()}</span>)}</div></div> : null}</section>; }
function Evidence({ plan }: { plan: Plan }) { return <div className="grid gap-3 sm:grid-cols-2"><section className="rounded-xl border border-emerald-300/15 bg-emerald-300/[.035] p-4"><div className="flex items-center gap-2"><CircleCheck className="h-4 w-4 text-emerald-300" /><h4 className="text-[10px] font-semibold uppercase tracking-[.15em] text-emerald-200">Why this setup</h4></div><p className="mt-2 text-sm font-semibold text-slate-100">Technical evidence from validated inputs</p><ul className="mt-3 space-y-1.5 text-xs leading-5 text-slate-300">{plan.evidence.slice(0, 5).map(item => <li key={item}>• {item}</li>)}</ul></section><section className="rounded-xl border border-amber-300/15 bg-amber-300/[.035] p-4"><div className="flex items-center gap-2"><CircleX className="h-4 w-4 text-amber-300" /><h4 className="text-[10px] font-semibold uppercase tracking-[.15em] text-amber-200">Risk factors</h4></div><p className="mt-2 text-sm font-semibold text-slate-100">Opportunity {plan.opportunityScore ?? "UNAVAILABLE"} · Regime {plan.regimeScore ?? "UNAVAILABLE"}</p><ul className="mt-3 space-y-1.5 text-xs leading-5 text-slate-300">{plan.risks.length ? plan.risks.slice(0, 5).map(item => <li key={item}>• {item}</li>) : <li>• No negative technical component is currently recorded.</li>}</ul></section></div>; }
function ProviderHealthPanel({ providers }: { providers: ProviderHealth[] }) { return <section className="rounded-2xl border border-white/[.08] bg-white/[.015] p-5" aria-label="Provider health"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-cyan-200">Provider health</p><h3 className="mt-1 text-sm font-semibold text-slate-100">Current scanner evidence — read only</h3></div><p className="max-w-xl text-xs leading-5 text-slate-400">HTTP 451 remains ineligible. A fallback is used only when all required timeframes form one validated provider bundle.</p></div><div className="mt-4 grid gap-3 xl:grid-cols-3">{providers.map(provider => <article key={provider.provider} className="rounded-xl border border-white/[.08] bg-slate-950/35 p-3"><div className="flex items-start justify-between gap-2"><div><h4 className="text-xs font-semibold text-slate-100">{provider.provider}</h4><p className={`mt-1 text-[10px] font-semibold ${provider.status === "LIVE" ? "text-emerald-200" : provider.status === "PARTIAL" ? "text-amber-200" : "text-rose-200"}`}>{provider.status}</p></div><span className="text-[10px] text-slate-500">{provider.supportedTimeframes.length ? provider.supportedTimeframes.map(value => value.toUpperCase()).join(" / ") : "No technical timeframe"}</span></div><dl className="mt-3 space-y-1 text-[10px] leading-4 text-slate-400"><div><dt className="inline text-slate-500">Last success: </dt><dd className="inline">{timestamp(provider.lastSuccessfulAt)}</dd></div><div><dt className="inline text-slate-500">Last failure: </dt><dd className="inline">{timestamp(provider.lastFailureAt)}</dd></div><div><dt className="inline text-slate-500">Classification: </dt><dd className="inline">{provider.failureClassification ?? "NONE"}</dd></div><div><dt className="inline text-slate-500">Validated symbols: </dt><dd className="inline">{provider.validatedSymbols.length || "None"}</dd></div></dl><p className="mt-3 border-t border-white/[.06] pt-2 text-[10px] leading-4 text-slate-500">{provider.note}</p></article>)}</div></section>; }
function TextList({ title, items, tone }: { title: string; items: string[]; tone: "amber" | "cyan" }) { const color = tone === "amber" ? "border-amber-300/15 bg-amber-300/[.035] text-amber-100" : "border-cyan-300/15 bg-cyan-300/[.035] text-cyan-100"; return <section className={`rounded-xl border p-3 ${color}`}><h4 className="text-[10px] font-semibold uppercase tracking-[.14em]">{title}</h4><ul className="mt-2 space-y-1 text-xs text-slate-200">{items.length ? items.map(item => <li key={item}>• {item}</li>) : <li>• UNAVAILABLE</li>}</ul></section>; }
function Level({ label, value, note, tone = "neutral" }: { label: string; value: string; note: string; tone?: "neutral" | "positive" | "risk" }) { const color = tone === "positive" ? "text-emerald-200" : tone === "risk" ? "text-rose-200" : "text-cyan-100"; return <div className="rounded-xl border border-white/[.07] bg-white/[.02] p-3"><span className="block text-[9px] font-semibold uppercase tracking-[.13em] text-slate-500">{label}</span><strong className={`mt-1 block break-words font-mono text-sm ${color}`}>{value}</strong><p className="mt-2 text-[10px] leading-4 text-slate-500">{note}</p></div>; }
function StatusCard({ label, value, tone }: { label: string; value: string; tone: "cyan" | "amber" | "violet" }) { const color = tone === "cyan" ? "text-cyan-100 border-cyan-300/15 bg-cyan-300/[.035]" : tone === "amber" ? "text-amber-100 border-amber-300/15 bg-amber-300/[.035]" : "text-violet-100 border-violet-300/15 bg-violet-300/[.035]"; return <div className={`rounded-xl border p-4 ${color}`}><span className="text-[9px] font-semibold uppercase tracking-[.14em] opacity-70">{label}</span><p className="mt-2 text-xs font-medium">{value}</p></div>; }
function Loading() { return <div className="grid min-h-[40vh] place-items-center"><div className="text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-cyan-200" /><p className="mt-3 text-sm text-slate-400">Validating multi-timeframe setup inputs…</p></div></div>; }
function ErrorPanel({ detail }: { detail: string }) { return <div className="rounded-xl border border-rose-300/25 bg-rose-300/[.06] p-4 text-sm text-rose-100"><strong>Setup intelligence unavailable.</strong><p className="mt-1 text-xs text-rose-100/75">{detail}</p></div>; }
function Empty() { return <div className="rounded-2xl border border-dashed border-white/[.12] p-8 text-center text-sm text-slate-400">No setup response is available. The workspace will not construct a fallback opportunity.</div>; }
