import { useMemo, useState } from "react";
import { Activity, ArrowLeft, Plus, RefreshCw, Search, Trash2, WifiOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { OpportunityCard } from "./OpportunityCard";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { usePwaStatus } from "@/pwa/PwaStatus";
import { toast } from "sonner";

export function WatchlistWorkspace({ onBack, onInspectAsset }: { onBack: () => void; onInspectAsset: (assetId: string) => void }) {
  const { isAuthenticated } = useAuth();
  const { online } = usePwaStatus();
  const [search, setSearch] = useState("");
  const [adding, setAdding] = useState(false);
  const utils = trpc.useUtils();
  const watchlistQuery = trpc.crypto.watchlist.useQuery(undefined, { enabled: isAuthenticated, refetchOnWindowFocus: false, staleTime: 30_000 });
  const scannerQuery = trpc.crypto.scanner.useQuery(undefined, { refetchOnWindowFocus: false, staleTime: 45_000, retry: 1 });
  const addMutation = trpc.crypto.addWatchlistAsset.useMutation({ onSuccess: async () => { await utils.crypto.watchlist.invalidate(); setAdding(false); setSearch(""); toast.success("Asset added to Watchlist"); }, onError: error => toast.error(error.message) });
  const removeMutation = trpc.crypto.removeWatchlistAsset.useMutation({ onSuccess: async () => { await utils.crypto.watchlist.invalidate(); toast.success("Asset removed from Watchlist"); }, onError: error => toast.error(error.message) });
  const watchedIds = watchlistQuery.data ?? [];
  const rows = scannerQuery.data?.rows ?? [];
  const watchedRows = useMemo(() => watchedIds.map(id => rows.find(row => row.asset.id === id)).filter(Boolean), [rows, watchedIds]);
  const candidates = useMemo(() => rows.filter(row => !watchedIds.includes(row.asset.id)).filter(row => `${row.asset.symbol} ${row.asset.name}`.toLowerCase().includes(search.trim().toLowerCase())).slice(0, 12), [rows, search, watchedIds]);
  const add = (assetId: string) => { if (!online || addMutation.isPending) return; addMutation.mutate({ assetId }); };
  const remove = (assetId: string) => { if (!online || removeMutation.isPending) return; removeMutation.mutate({ assetId }); };
  if (!isAuthenticated) return <section className="mx-auto max-w-5xl rounded-2xl border border-amber-300/20 bg-amber-300/[.04] p-6 text-slate-100"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-amber-200">Watchlist</p><h2 className="mt-2 text-2xl font-semibold">Sign in to view your Watchlist</h2><p className="mt-2 text-sm text-slate-400">Your followed assets are private and owner-scoped.</p><Button className="mt-5 min-h-11" onClick={() => window.location.href = "/api/oauth/login"}>Sign in</Button></section>;
  return <section className="mx-auto max-w-[1500px] space-y-5"><header className="flex flex-wrap items-start justify-between gap-4"><div><Button variant="ghost" onClick={onBack} className="-ml-3 mb-2 min-h-11 text-slate-400"><ArrowLeft className="mr-2 h-4 w-4" />Dashboard</Button><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-cyan-300">Monitor / Watchlist</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Your monitored assets</h1><p className="mt-1 text-sm text-slate-400">Watchlist assets are followed references, not setups, alerts, or simulated positions.</p></div><div className="flex items-center gap-2"><span className="rounded-full border border-white/[.1] px-3 py-1.5 text-xs text-slate-400">{watchedIds.length} assets</span><Button variant="outline" onClick={() => watchlistQuery.refetch()} disabled={!online || watchlistQuery.isFetching} className="min-h-11 border-white/[.1]"><RefreshCw className={watchlistQuery.isFetching ? "mr-2 h-4 w-4 animate-spin" : "mr-2 h-4 w-4"} />Refresh</Button><Button onClick={() => setAdding(value => !value)} disabled={!online} className="min-h-11 bg-cyan-300 text-slate-950 hover:bg-cyan-200"><Plus className="mr-2 h-4 w-4" />Add Asset</Button></div></header>
    {!online ? <div className="flex items-center gap-2 rounded-xl border border-amber-300/20 bg-amber-300/[.04] p-3 text-sm text-amber-100"><WifiOff className="h-4 w-4" />READ ONLY / OFFLINE — Watchlist mutations are disabled until connection returns.</div> : null}
    {adding ? <div role="dialog" aria-label="Add asset to Watchlist" className="rounded-2xl border border-cyan-300/20 bg-[#0a111e] p-4 shadow-2xl"><div className="flex items-center gap-2"><Search className="h-4 w-4 text-cyan-200" /><Input autoFocus value={search} onChange={event => setSearch(event.target.value)} placeholder="Search assets..." className="min-h-11 border-white/[.1] bg-white/[.03]" /></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{candidates.length ? candidates.map(row => <button key={row.asset.id} type="button" onClick={() => add(row.asset.id)} className="flex min-h-11 items-center justify-between rounded-xl border border-white/[.08] bg-white/[.025] px-3 text-left hover:border-cyan-300/30"><span><strong className="block text-sm text-slate-100">{row.asset.symbol}</strong><span className="text-xs text-slate-500">{row.asset.name}</span></span><Plus className="h-4 w-4 text-cyan-200" /></button>) : <p className="col-span-full p-3 text-sm text-slate-500">No canonical asset matches.</p>}</div></div> : null}
    {watchlistQuery.isLoading ? <div className="rounded-2xl border border-white/[.08] p-8 text-center text-sm text-slate-400">Loading Watchlist…</div> : watchlistQuery.error ? <div className="rounded-2xl border border-rose-300/20 bg-rose-300/[.04] p-6"><p className="font-semibold text-rose-100">Watchlist unavailable</p><p className="mt-1 text-sm text-rose-100/70">Unable to load your Watchlist.</p><Button variant="outline" onClick={() => watchlistQuery.refetch()} className="mt-4 min-h-11 border-rose-300/20">Retry</Button></div> : watchedRows.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{watchedRows.map(row => row ? <div key={row.asset.id} className="relative"><OpportunityCard data={{ assetId: row.asset.id, symbol: row.asset.symbol, name: row.asset.name, setupType: row.score?.setupType, status: row.score ? "SCORED" : row.dataStatus.some(status => status.status === "unavailable") ? "DATA UNAVAILABLE" : "UNAVAILABLE", score: row.score?.score, direction: row.score?.direction?.toUpperCase(), why: row.score?.explanation ?? row.dataStatus.find(status => status.status !== "live")?.message ?? "Current validated market state is unavailable." }} onView={() => onInspectAsset(row.asset.id)} /><Button type="button" aria-label={`Remove ${row.asset.symbol} from Watchlist`} variant="ghost" onClick={() => remove(row.asset.id)} disabled={!online || removeMutation.isPending} className="absolute right-3 top-3 min-h-11 px-2 text-slate-500 hover:text-rose-200"><Trash2 className="h-4 w-4" /></Button></div> : null)}</div> : <div className="rounded-2xl border border-dashed border-white/[.12] bg-white/[.02] p-10 text-center"><Activity className="mx-auto h-7 w-7 text-slate-500" /><h2 className="mt-3 text-lg font-semibold">You are not watching any assets yet.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-400">Add assets to quickly monitor their latest validated market state.</p><Button onClick={() => setAdding(true)} disabled={!online} className="mt-5 min-h-11 bg-cyan-300 text-slate-950 hover:bg-cyan-200"><Plus className="mr-2 h-4 w-4" />Add Asset</Button></div>}
  </section>;
}
